# Introduction {#sec-intro}
Uncertainty visualisation is a relatively new field, but it has been poorly defined.
Uncertainty itself is a vague term; each paper seems to take the meaning of it as a given, so the visualisation of it is fraught with disagreement and conflict over definitions, applications, and best practices littering the literature.
Incorporating uncertainty into our visualisations is important for transparent graphics and improved decision making, with some authors considering ignoring uncertainty to be tantamount to fraud [@Hullman2020a].
Despite the importance of uncertainty visualisation, the field has struggled to create an overarching cohesive theory, with current best practices in plot design remaining ad hoc and context specific [@MacEachren2005].
These issues would be resolved if uncertainty were formalised as the existing structures for statistical graphics, such as the *grammar of graphics* [@Leland2005] and its implementation in `ggplot2` [@ggplot2].
The formalisation of uncertainty in the grammar of graphics has remained difficult due to the confusing of uncertainty, a term which has as many definitions as there are discussions on the topic [@Spiegelhalter2017].

This thesis attempts to close these gaps by providing a comprehensive analysis of uncertainty visualisation, including its definition, practical application, and evaluation.
First, we deal with the vague definition of uncertainty and interrogate the current meaning of the term uncertainty visualisation.
Building on foundations in statistical inference and graphics, we redefine what it means to visualise uncertainty and establish a statistical foundation for the goals of the field. 
Next, we leverage this foundation to formalise uncertainty visualisation in the grammar of graphics, implemented in the ggplot2 extension `ggdibbler`. 
We show that the formalisation goes beyond mathematical pedantry and allows us to build a powerful mathematical framework for uncertainty visualisation that can be used for exploratory data analysis, an application that has remained just out of reach of the field of decades.
Finally, tie these ideas together in an evaluation study on the perception of uncertainty visualisations, and show that the formalisation we designed is not only flexible, but it also allows us to test the uncertainty visualisation goals in the first chapter by giving us a framework to understand why some plots appear differently to others.
This validation is done using a novel experiment design, by drawing parallels in the goals of uncertainty visualisation and standard colour blind tests, repurposing the standard Ishihara colour blind test for uncertainty visualisation.
These chapters cover ground in every area touched by statistical graphics, philosophy, statistics, computer science, and psychometrics. We set the foundations for a new approach to uncertainty visualisation that allows us to integrate variance into our visualisations, no matter the context.

## Thesis Outline
The thesis is structured as follows.

@sec-first-paper provides a comprehensive review of the uncertainty visualisation literature. Existing reviews in the field take the purpose of an uncertainty visualisation to be self-evident, which results in a large amount of conflicting information.  The most common approach communicates uncertainty as a probability or a distribution, and focuses on showing the uncertainty as an isolated variable disconnected from its context. We contrast these visualisations with approaches that view uncertainty as noise that should be incorporated to give a holistic view of our data. We coin the term “signal suppression” to describe a visualisation that is designed for preventing false conclusions, as the approach demands that the signal (i.e., the conclusions drawn from the estimates) is suppressed by the noise (i.e., the variance on those estimates). We provide motivation for viewing signal suppression as the most worthwhile goal in uncertainty visualisation, and argue that visualisations that display uncertainty as an isolated variable should not be considered uncertainty visualisations at all. We further discuss difficulties in creating and evaluating the effectiveness of these plots, which further motivates the following chapters of this thesis.
 
@sec-second-paper introduces a new R package, ggdibbler. In @sec-first-paper we discussed the run-on effects of the ambiguous definition of uncertainty. These problems included difficulty incorporating uncertainty into the grammar of graphics framework, which leads to software that does not always behave in ways that users would expect. @sec-second-paper closes this gap by discussing the theoretical implications of including uncertainty in the grammar of graphics, and introducing ggdibbler, a ggplot extension that allows us to visualise uncertainty holistically and prevent false signals. We illustrate how ggdibbler can be seamlessly integrated into existing visualisation workflows and demonstrate its usefulness by looking at examples that use ggdibbler to incorporate uncertainty into a choropleth map.

@sec-third-paper presents a user study that evaluates human perception of uncertainty visualisations. @sec-first-paper highlighted the difficulty in evaluating uncertainty visualisations, as the uncertainty must be evaluated as noise rather than signal, and provides some suggestions for experimental methods. This section applies the suggested experimental methods and identifies which graphics, implemented by the ggdibbler software introduced in @sec-second-paper, are effective tools for signal suppression. The experiment in this section is motivated by a case study specific to problems faced by AEMO. The transition to renewable energy results in a large amount of uncertainty in Australia's energy demands, which also demands a better understanding of the uncertainty if we are to make the transition without issue.

The material in @sec-first-paper was submitted to the journal *Annual Reviews of Statistics and Its Applications* for publication, and is now an invited contribution to Volume 14 of the Journal. The `ggdibbler` software outlined in @sec-second-paper has been submitted to *CRAN*. The contribution in @sec-second-paper of this thesis was presented at *useR! 2025* in Durham, North Carolina, in August 2025 and *ASC 2026* in Perth, Western Australia, in December 2025. The material in @sec-second-paper has been submitted to the *Journal of Computational Graphics and Statistics*. The material in @sec-third-paper has been submitted as a conference paper to *IEEE VIS 2026*.
